# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqdGvrz4Dkc94IDoxwTwKGKnFROF_uef
"""

# app.py

import streamlit as st
import joblib
import numpy as np

# Load trained model
model = joblib.load('house_price_model.pkl')

st.title("🏠 House Price Prediction App")

st.markdown("Enter property details below to predict the price.")

# Input fields
square_meters = st.slider("Square Meters", 20, 500, 100)
num_rooms = st.slider("Number of Rooms", 1, 10, 3)
floors = st.slider("Number of Floors", 1, 5, 1)
attic = st.slider("Attic Size (m²)", 0, 100, 10)
basement = st.slider("Basement Size (m²)", 0, 100, 10)
garage = st.slider("Garage Size (m²)", 0, 100, 10)
city_part_range = st.selectbox("City Part Range (1 = Low, 10 = High)", list(range(1, 11)))

# Binary features
has_pool = st.checkbox("Has Pool")
has_yard = st.checkbox("Has Yard")
is_new = st.checkbox("Is Newly Built")
has_storage = st.checkbox("Has Storage Room")
has_storm_protector = st.checkbox("Has Storm Protector")

# Collect user input
features = np.array([[
    square_meters, num_rooms, floors, attic, basement, garage,
    city_part_range, int(has_pool), int(has_yard), int(is_new),
    int(has_storage), int(has_storm_protector)
]])

# Predict
if st.button("Predict Price"):
    prediction = model.predict(features)[0]
    st.success(f"Estimated House Price: ${prediction:,.2f}")